apiVersion: v1
kind: ConfigMap
metadata:
  name: py-app-config
data:
  APP_NAME: "PY Learning Project (k8s)"
  DEBUG: "false"
  DATABASE_URL: "sqlite:///./app.db"
  CHAT_MODEL: "claude-3-5-sonnet-latest"
  LLM_TIMEOUT: "30.0"
  SUPABASE_URL: "https://ygowhftzbyzpjjjycjvj.supabase.co"
